language: python
sudo: required

python:
  - "3.6"

services:
  - docker

before_install:
  - docker build -t chat -f Dockerfile .
  - docker build -t chat-tests -f Dockerfile-tests .
  - docker image ls

install:
  - pip install -r requirements.txt
  - pip install pycodestyle

script:
  - pycodestyle chat.py chat_test.py --ignore=E501
  - docker run -p 4000:8888 chat-tests
#  - nosetests
