language: python
sudo: required

python:
  - "3.6"

services:
  - docker

before_install:
  - docker build -t chat .
  - docker image ls

install:
  - pip install -r requirements.txt
  - pip install pycodestyle

script:
  - pycodestyle chat.py chat_test.py --ignore=E501
#  - nosetests
